packages:
  - apps/*
  - packages/*
  - video

ignoredBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - msgpackr-extract
  - prisma
  - sharp
